stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/config/config.yaml
      - src/config/model_params.py
    outs:
      - artifacts/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_ingestion.py
      - artifacts/raw
      - src/config/config.yaml
      - src/config/model_params.py
    outs:
      - artifacts/processed
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/data_ingestion.py
      - src/data_preprocessing.py
      - src/config/config.yaml
      - src/config/model_params.py
      - artifacts/processed
    outs:
      - artifacts/models





